### ISSUE TITLE
Error after restarting config-api deployment

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-cloud-native#19]
**Describe the bug**
When restarting config-api deployment, DB seems to be re-seeded creating duplicate objects like scopes.

**To Reproduce**
1. Install Jans with config-api
2. execute a kubectl rollout restart to jans-config-api deployment
3. See jans-config-api doesn't start

**Expected behavior**
After restart of pod config-api should be able to start without any problems.

**Screenshots**
Pod logs below after deployment restart.

INFO - jans.pycloudlib.wait - 2021-02-12 18:26:52,608 - Config is ready INFO - jans.pycloudlib.wait - 2021-02-12 18:26:52,637 - Secret is ready INFO - jans.pycloudlib.wait - 2021-02-12 18:26:53,022 - LDAP is ready
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =================================================================
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =============  STARTING API APPLICATION  ========================
18:26:58 INFO  [io.ja.co.ConfigApiApplication] (main) =================================================================
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loading base configuration /etc/jans/conf/jans.properties
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loaded base configuration:{certsDir=/etc/certs, fido2_ConfigurationEntryDN=ou=fido2,ou=configuration,o=jans, confDir=, jansAuth_ConfigurationEntryDN=ou=jans-auth,ou=configuration,o=jans, persistence.type=ldap, pythonModulesDir=/opt/jans/python/libs:/opt/jython/Lib/site-packages}
18:26:58 INFO  [io.ja.co.co.ConfigurationFactory] (main) Loading configuration from 'ldap' DB...
18:26:58 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.op.im.LdapConnectionProvider] (main) Attempting to create connection pool: 1
18:26:59 INFO  [io.ja.or.ld.im.LdapEntryManagerFactory] (main) Created LdapEntryManager: io.jans.orm.ldap.operation.impl.LdapOperationServiceImpl@3f81621c
18:26:59 INFO  [io.ja.co.co.ConfigurationFactory] (main) Configuration loaded successfully.
18:26:59 INFO  [io.ja.co.co.ConfigurationFactory] (main) =============  createAuthorizationService() - ConfigurationFactory.getApiProtectionType() = oauth2
18:26:59 ERROR [io.ja.co.au.ConfigApiResourceProtectionService] (main) 2 Scope with same name.
18:26:59 ERROR [io.ja.co.co.ConfigurationFactory] (main) Failed to create AuthorizationService instance: javax.ws.rs.WebApplicationException: Multiple Scope with same name - https://jans.io/oauth/config/acrs.readonly
        at io.jans.configapi.auth.ConfigApiResourceProtectionService.createScopeIfNeeded(ConfigApiResourceProtectionService.java:105)
        at io.jans.configapi.auth.ConfigApiResourceProtectionService.verifyResources(ConfigApiResourceProtectionService.java:71)

**Additional context**
This deployment is using _dev docker images

**Comment by moabu** [comment]
issue is confirmed. Duplicated entries are being created and the source seem to be the app itself which fails to identify with the defined scopes.

**Comment by moabu** [comment]
@ruiengana can you please redeploy with `1.0.0_dev` images. LDAP is populated with duplicate entries so you have two options , either access ldap with an ldap browser and delete all replicated scopes and then pull the latest `1.0.0_dev` image by deleting the pod for config-api or simply redeploy jans.  You should be able to scale as well now. 

```bash
NAME                                READY   STATUS      RESTARTS   AGE
jans-config-pn8rb                   0/1     Completed   0          7m40s
jans-opendj-0                       1/1     Running     0          7m40s
jans-scim-58fdcc54ff-p62mf          1/1     Running     1          7m40s
jans-fido2-65fd6b5957-8km7l         1/1     Running     1          7m40s
jans-auth-server-576bbcd7d9-swqpr   1/1     Running     1          7m40s
jans-persistence-2rpsh              0/1     Completed   0          7m40s
jans-config-api-649b8fb8c8-nkrbj    1/1     Running     1          7m40s
jans-config-api-649b8fb8c8-9q4r6    1/1     Running     0          39s
```

Issue bug related in the source : https://github.com/JanssenProject/jans-config-api/issues/16#issuecomment-780004551 
ref: https://github.com/JanssenProject/jans-pycloudlib/commit/8c56ce10f32743ddb8925b8cf5315d5b1db22faf

**Comment by ruiengana** [comment]
@moabu I can confirm we can now restart config-api, hwoever, application logs seem to suggests scopes are being changed / replaced on restart, is that correct?

**Comment by moabu** [comment]
@ruiengana the scopes shoudn't be changed. It just checks if the scope exists or not. You can verify that by looking at your scopes in an ldap browser.
