### ISSUE TITLE
SCIM APIs not protected by default

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-cloud-native#8]
**Describe the bug**
When SCIM is used, SCIM APIs are not protected by default allowing anyone to create, update, delete Users.

**To Reproduce**
1. Install Jans
2. Execute GET call to https://<server>/jans-scim/restv1/v2/Users

**Expected behavior**
I would expect access to SCIM API access to be protected by default similar to Config API.

**Comment by moabu** [comment]
@ruiengana this should probably be placed at https://github.com/JanssenProject/jans-scim

I have moved this issue there. 
https://github.com/JanssenProject/jans-scim/issues/2

**Comment by ruiengana** [comment]
After latest patch, we are now seeing the following in SCIM logs

```
INFO  scim.auth.uma.ScimUmaProtectionService ScimUmaProtectionService.java:99- ==== SCIM Service call intercepted ====
INFO  scim.auth.uma.ScimUmaProtectionService ScimUmaProtectionService.java:100- Authorization header  found
INFO  scim.auth.uma.ScimUmaProtectionService ScimUmaProtectionService.java:114- Please activate UMA or test mode to protect your SCIM endpoints. Read the Gluu SCIM docs to learn more
```

Is Jans SCIM docker image setting up API protection?
Also, would be really great to bootstrap a SCIM Client with token auth method = client_secret_basic (similar to jca_client) to use in Jans CLI.

**Comment by nynymike** [comment]
Regarding bootstrapped client, you can do this with the config api.  If you think it's a bug, please open another issue.

**Comment by moabu** [comment]
> Is Jans SCIM docker image setting up API protection?

No. Right now its built in as it should be. You may activate test mode directly following this link'(https://github.com/JanssenProject/jans-scim#test-mode). 

> Also, would be really great to bootstrap a SCIM Client with token auth method = client_secret_basic (similar to jca_client) to use in Jans CLI.

Yes we might add the ability to do this with a flag in helm to ease things.

**Comment by ruiengana** [comment]
> > Also, would be really great to bootstrap a SCIM Client with token auth method = client_secret_basic (similar to jca_client) to use in Jans CLI.
> 
> Yes we might add the ability to do this with a flag in helm to ease things.

A SCIM client similar to Config API is a *absolute* must for us, without it we can't manage users :(

**Comment by moabu** [comment]
I see. Can you not use the jans-cli to bootstrapping the client though ?

**Comment by ruiengana** [comment]
> I see. Can you not use the jans-cli to bootstrapping the client though ?

We can, but similarly that Config API has a client created from install, SCIM API should too. Why differentiate?

**Comment by moabu** [comment]
> We can, but similarly that Config API has a client created from install, SCIM API should too. Why differentiate?

There is a difference . You can notice that UMA here can be activated. I need to discuss this with my team to weight out adding both(Test mode, UMA mode) or perhaps one protection route.
